apiVersion: apps/v1
kind: Deployment
metadata:
  name: meupostgres
spec:
  selector: 
    matchLabels: 
      app: meupostgres
  replicas: 1
  template:
    metadata:
      labels:
        app: meupostgres
    spec:
      volumes:
        - name: persistent-volume-meupostgres
          persistentVolumeClaim:
            claimName: pv-claim-postgres
      containers:
        - name: meupostgres
          image: postgres:14.2
          env:
            - name: POSTGRES_PASSWORD
              value: larissinha
          ports:
            - containerPort: 5432
              name: "database-server"
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: persistent-volume-meupostgres
---
apiVersion: v1
kind: Service
metadata:
  name: meupostgres-cip
spec:
  type: ClusterIP
  ports: 
    - port: 5432
  selector: 
    app: meupostgres
---
apiVersion: v1
kind: Service
metadata:
  name: meupostgres-lb
spec:
  type: LoadBalancer
  ports: 
    - port: 5432
  selector: 
    app: meupostgres
